# ===================================
# Development Profile
# ===================================
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/commerce_platform_dev}

logging.level.com.crm.commerce.platform=INFO
#logging.level.org.springframework.data.mongodb=DEBUG
