# ===================================
# Staging Profile
# ===================================
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.redis.password=${REDIS_PASSWORD}

logging.level.root=INFO
logging.level.com.crm.commerce.platform=INFO

management.endpoint.health.show-details=always
